# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb72d70f7a46743db49b3fb069395a4a3563aa581d046f905ec90fa9a3bf10527aba76ae6b7323181a9ae1fcfa02e3a1c9c4527a37b3a3bb450f07e1d496da9c

test:
  secret_key_base: 02504dbcaeb9de9e99532ffa9571a663c80043b82d03252b5bcf0441150dd9ae13223d13fcb5642b1895224870d43fd5a1ba6455159683a533685dab04039798

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
